### ISSUE TITLE
Is pg_pathman is supporting native/declarative partitioning in pg10

### ISSUE THREAD

**Issue by kotsachin** [postgrespro/pg_pathman#133]
### Is pg_pathman is supporting native/declarative partitioning in pg10

I would like know below details about pg_pathman:
1. Is pg_pathman supporting native/declarative partitioning in g10? If not, is there any plan for it?
2. Is pg_pathman ready for production?

Regards,
Sachin

**Comment by funbringer** [comment]
Hi @kotsachin,

> Is pg_pathman supporting native/declarative partitioning in g10? If not, is there any plan for it?

What meaning do you put in "declarative partitioning"? Is it just syntax, or an engine inside of PostgreSQL that makes it work? It matters a lot, since pg_pathman is a partitioning engine itself (it manages partitions, performs pruning etc), which means that we can add some support for declarative syntax, but you will never be able to create a table that's managed by both pg_pathman and native engine at the same time.

In the upcoming release (1.5) we're going to add basic support for declarative syntax (DDL statements will be hooked by pg_pathman and translated into our API fuctions).

> Is pg_pathman ready for production?

* We strive to fix bugs as soon as possible;
* We aim to support pg_pathman until it becomes completely obsolete (compared to native partitioning);
* pg_pathman is tested in our private build farm on ~30 different distributions of Linux, Solaris and Windows;
* We know that there are people who use pg_pathman in production.

I guess that makes pg_pathman ready for production.

Hope this answers your questions.

**Comment by kotsachin** [comment]
Thanks for detail explanation. 
We are expecting support for declarative syntax from pg_pathman. And conversion of inheritance based partitions to declarative partitions in PostgreSQL. 
Hope declarative partition engine from PostgreSQL will be best in performance so no need to use hooks for pruning.
We will start using pg_pathman in our environment.

You can close this issue.
