### ISSUE TITLE
How does pg_pathman interact with postgres master-slave streaming replication?

### ISSUE THREAD

**Issue by ashu210890** [postgrespro/pg_pathman#138]
### Problem description

I have a decent idea of how streaming replication in postgres works, by tailing the WALs for new writes that come in. What I am having trouble understanding is which phase of a postgres write does pg_pathman come into picture i.e. before or after write to the WAL.

The high level question that I am trying to answer is that, if I partition tableA on master, can the slave still accept replication stream for tableA which does not have the partitions yet?

Also, what is the recommended way to partition with pg_pathman in a master-slave configuration?

### Environment

Postgres version: 9.5
pg_pathman version: 1.4

**Comment by funbringer** [comment]
Hi @ashu210890,

Thanks for your questions!

> I have a decent idea of how streaming replication in postgres works, by tailing the WALs for new writes that come in. What I am having trouble understanding is which phase of a postgres write does pg_pathman come into picture i.e. before or after write to the WAL.

There's nothing to worry about, everything should work smoothly. You should know that binary replica behaves as if it's a crashed instance of PostgreSQL that's trying to replay everything since last checkpoint. The only difference is that it's never going to end the process, as it's constantly accepting more and more WAL.

When you create a table, function, etc, the changes are recorded into `pg_catalog`, a namespace which knows everything about your relations. These are the changes that will occasionally be replayed on a binary replica.

This was a side note, just to state that there's no magic in replicas.

> The high level question that I am trying to answer is that, if I partition tableA on master, can the slave still accept replication stream for tableA which does not have the partitions yet?

That's a good question! First, we must remember that each and every operation is executed in a transaction. This effectively means that at any time we'll see a consistent result. If you've just a created partitioned table in a single transaction, you should wait until async replica catches up, and you'll be able to see the table in the following transaction. There's nothing special in pg_pathman in this regard, it just plays by the rules :)

> Also, what is the recommended way to partition with pg_pathman in a master-slave configuration?

There's no recommended way, it's completely up to you. However, logical replication is much more complicated, so it's better to use [pg_shardman](https://github.com/postgrespro/pg_shardman) (it's built on top of pg_pathman).

Hope this answers your questions.

**Comment by ashu210890** [comment]
Thanks @funbringer for the detailed explanation!
