### ISSUE TITLE
why have no effect after partition?

### ISSUE THREAD

**Issue by 474420502** [postgrespro/pg_pathman#145]
no  partition !
![default](https://user-images.githubusercontent.com/9397764/36014277-dce4cb82-0da3-11e8-9f54-19ad9df1c2e0.png)

partition 
![default](https://user-images.githubusercontent.com/9397764/36014297-fac28734-0da3-11e8-8835-f63f0070e09f.png)

after partition !
![default](https://user-images.githubusercontent.com/9397764/36014309-092a40fa-0da4-11e8-8139-a41f8f9a1d5f.png)

**Comment by funbringer** [comment]
Hi,

I don't see a problem here. Could you provide a few words describing the desired behavior?

**Comment by 474420502** [comment]
Thank you for the reply!  @funbringer 
After partitioning, the performance is not much improved.  TPS is still very low.

**Comment by 474420502** [comment]
(select * from partition_parent limit 1) that will scan the data of partition table.  is also slow.

**Comment by funbringer** [comment]
I'm sorry, but your problem still looks very vague to me. Partitioning does not necessarily make your queries run faster. If you partition table by `aid` column, only those queries that reference `aid` might work better. For instance:

```plpgsql
update pgbench_accounts set ... where aid = 5;
```

can be optimized, since we've partitioned `pgbench_accounts` by `aid` and it's compared to 5 which is const. However, these queries might become slower:

```plpgsql
select * from pgbench_accounts where tid = ...;
delete from pgbench_accounts where bid > 10;
-- etc
```

> (select * from partition_parent limit 1)

This query cannot be optimized. You literally have to scan each partition until you find at least 1 row.

**Comment by 474420502** [comment]
Thanks, I had found the best way to solve the question.
