### ISSUE TITLE
Migrating existing partitions to pg_pathman 

### ISSUE THREAD

**Issue by vmihailenco** [postgrespro/pg_pathman#25]
Assuming that I already use table inheritance to partition my table what I need to do to migrate to pg_pathman? My experiments show that I only need to execute

```
select create_partitions_from_range('notices', 'id', 0::bigint, -1::bigint, 22468047667200000);
```

to start using pg_pathman. Is that correct?

Please note that I had to use start_value=0 and end_value=-1 to prevent pg_statsman from creating any partitions... It is totally fine, but probably should be documented.

**Comment by funbringer** [comment]
The upcoming release will contain a function to add a parent table to `pathman_config`. It will perform certain checks to ensure that the table is integrated seamlessly, otherwise an error will be emitted.

**Comment by zilder** [comment]
This wasn't documented because we didn't expected that someone will use it that way : ) We've been already told that it would be useful feature to enable `pg_pathman` for existing partitioning. There is one main problem -- we should validate this existing setup to be sure that check constraints satisfy the certain format (e.g. for range partitioning it must be `attr >= const and attr < const`). If it's not then `pg_pathman` won't be able to use them to filter partitions.

**Comment by funbringer** [comment]
This function (`add_to_pathman_config()`) has been implemented in a6e426004ca174154c239fd8490cd89075db3be1. The upcoming release is going to provide it.

**Comment by vmihailenco** [comment]
Thanks - going to test it.

It is a bit strange that function has general name `add_to_pathman_config`, but expects `range` partitioning... I would expect something like `init_range_partitions` and you probably can autodetect range_interval in most cases by `max(attribute) - min(attribute)`. Just my 5 cents - thanks for your work.

**Comment by vmihailenco** [comment]
I get this when I try to use pg_pathman on existing partitions

```
goab_shard_test=# select public.add_to_pathman_config('notices', 'id', '22468047667200000');
ERROR:  constraint "pathman_545146_1_check" for partition "notices_y2016m01" does not exist
```

Do you have any ideas?

**Comment by funbringer** [comment]
To @vmihailenco:

This is due to the fact that HASH constraints have been dropped along with the pg_pathman, since they rely on function provided by the extension. There's nothing you can do to workaround this: once you've dropped pg_pathman, all HASH constraints are destroyed.

We could probably evaluate a hash of a partitioned column and restore check constraints, though. What do you think?

**Comment by vmihailenco** [comment]
>This is due to the fact that HASH constraints have been dropped along with the pg_pathman

I did not drop pg_pathman extension. Instead I created new database and new partitions. Also I am not sure which HASH constraints you mean, because I am using partitioning by range...

**Comment by funbringer** [comment]
to @vmihailenco:

> Instead I created new database and new partitions

So you did this (correct me if i'm wrong):

1) installed pg_pathman on new DB;
2) partitioned table by range;
3) deleted corresponding entry from `pathman_config`;
4) Got an error while trying to use `add_to_pathman_config`.

Right?

**Comment by alexign** [comment]
Hi!
Can you explain more thoroughly what do you want to do. 
Say I have my own partitioned table and want it migrate to pg_pathman partition scheme?

**Comment by funbringer** [comment]
To @vmihailenco:

> It is a bit strange that function has general name `add_to_pathman_config`

Actually, it's the main point of this function. It is intended to be used in case when you want to integrate a table which had been partitioned by pg_pathman a while ago, but was removed from `pathman_config` (e.g. the extension has been dropped). Thus it is designed to check if constraints with certain format and names exist on each partition.

> I would expect something like init_range_partitions and you probably can autodetect range_interval in most cases by max(attribute) - min(attribute)

It is up to you to select the interval you'd like to use. It will only be used for new partitions, not the old ones. I don't see a desperate need for this feature, since it would make validation much slower. If you really crave for this feature, you could make a tiny wrapper function to calculate the interval using your formula :)

> but expects range partitioning... 

Actually, interval parameter is declared as `range_interval TEXT DEFAULT NULL`, with NULL meaning that table is partitioned by HASH, so this function is universal.

**Comment by vmihailenco** [comment]
>Say I have my own partitioned table and want it migrate to pg_pathman partition scheme?

Exactly. See my very first post.

>Thus it is designed to check if constraints with certain format and names exist on each partition.

Okay. My intention here is to migrate existing partitioned table to pg_pathman. So I certainly don't have some constraints. Can you please advise what should I do? On master I could use

```
select create_partitions_from_range('notices', 'id', 0::bigint, -1::bigint, 22468047667200000);
```

which seemed to work fine on simple tests...

**Comment by funbringer** [comment]
To @vmihailenco:

> Can you please advise what should I do?

Probably the most generic advice: you could create a completely new non-partitioned table (say, `part_new`), then partition it using `pg_pathman` (setting your interval of choice) into zero or 1 partitions, and after that:

```sql
INSERT INTO part_new SELECT * FROM __your_table__;
```

And `pg_pathman` will create new partitions for your data automatically.

**Comment by vmihailenco** [comment]
>Probably the most generic

...obvious and useless - no offense, but my question implied that I want to avoid reinserting several terrabytes of data.

**Comment by funbringer** [comment]
You know, you can use pg_pathman however you like, it's free as in beer. Like, whatever works for you.


> my question implied that I want to avoid reinserting several terrabytes of data.

Then why don't you write your own migration script and assign a valid check constraint for each partition?

You have everything you need:

1) `build_check_constraint_name_attname()` & `build_check_constraint_name_attnum()` can provide a correct name for each constraint.

2) `build_range_condition(attname, min_val, max_val)` can generate a valid constraint format. In conjunction with `min(...)` and `max(...)` aggregates it does 95% of the job. The only thing you should be aware of is that upper bound is excluded from partition's interval, so you should use `max(...) +1` or something more adequate to your needs.

IMO this is the most ideomatic way to migrate, but if you've already figured out a simpler way to perform such a task, why bother?

**Comment by alexign** [comment]
So if you want to "avoid reinserting several terrabytes of data" you need to write your own converter(we dont know your partitioned table structure, constraint on them and so on) or as another option you can write email to info@postgrespro.ru and describe all of you wishes to our sales department.
Best regards

**Comment by vmihailenco** [comment]
Why you even bother to write that bullshit? It worked with `select create_partitions_from_range`. Now it does not.

>write email to info@postgrespro.ru and describe all of you wishes to our sales department.

F*ck you too very much, best wishes!
