### ISSUE TITLE
Unable to spawn new partitions on insertion

### ISSUE THREAD

**Issue by IVolzhev** [postgrespro/pg_pathman#44]
When table owner set to non-default role, creating a new partition terminates with error. Please see test script below:

```
drop role if exists oimc_owner;
drop table if exists raw_flows cascade; 

create role oimc_owner nologin nosuperuser;

--
--
create table if not exists raw_flows(
  rawf_begin_connection_time      timestamp not null,
  rawf_client_address             inet not null
)
with (oids = false);
--
alter table raw_flows owner to oimc_owner;
--
select
create_range_partitions(
  'raw_flows',
  'rawf_begin_connection_time',
  date_trunc('day', localtimestamp)::timestamp,
  '1 day'::interval,
  1
);

insert into raw_flows values (now()::timestamp, '127.0.0.1');
insert into raw_flows values (now()::timestamp + interval '1 day', '127.0.0.1');
```
This script causes error:
```
ERROR:  Attempt to spawn new partitions of relation "raw_flows" failed
HINT:  See server log for more details.
```

If the `alter table raw_flows owner to oimc_owner` statement is removed, all works perfectly.

**Comment by funbringer** [comment]
hi @IVolzhev,

Sorry for the delay. `pg_pathman` may use a special background worker called `SpawnPartitionsWorker` to create new partitions. Let me show you what's happening here.

Let's say we have a partitioned table `test` with two children: 

```plpgsql
select * from pathman_partition_list where parent = 'test'::regclass;
 parent | partition | parttype | partattr | range_min | range_max 
--------+-----------+----------+----------+-----------+-----------
 test   | test_1    |        2 | val      | 1         | 501
 test   | test_2    |        2 | val      | 501       | 1001
(2 rows)

/* create new user and give ownership */
create user logoff with nologin;
alter table test owner to logoff;

insert into test values(1001);
ERROR:  Attempt to spawn new partitions of relation "test" failed
HINT:  See server log for more details.
```

This is what actually happens under the hood:

```
FATAL:  role "logoff" is not permitted to log in
LOG:  worker process: SpawnPartitionsWorker (PID 21507) exited with exit code 1
ERROR:  Attempt to spawn new partitions of relation "qq" failed
HINT:  See server log for more details.
STATEMENT:  insert into qq values(31);
```

Currently this worker tries to connect to PostgreSQL as a table's owner, which is impossible in your case. Unfortunately, there's no simple way to show the warning message directly, since it has to be transmitted from a separate process. This is why we have to redirect user to server log - to let him know what the problem is.

We're going to rework both error handling and connection settings sooner or later. Would you like to be notified of progress?

**Comment by IVolzhev** [comment]
Hi @funbringer.
 
Thank yor for explanation. As far as I understand I have to grant login privilege for new table owner. I had tried to do that, but I got the same result until I granted superuser privilege for new owner:

`create role oimc_owner login superuser password 'oimc';`

Is it really required to grant superuser privilege?

**Comment by funbringer** [comment]
> Is it really required to grant superuser privilege?

No, it's not supposed to require su privileges. However, are you sure it's the same error? Don't forget that you should also grant INSERT to the user that is going to insert new rows.

**Comment by IVolzhev** [comment]
Hi @funbringer 
You are right. I have to grant insert into table privilege and select from sequence.

Thank you so much!
