### ISSUE TITLE
the table is lost

### ISSUE THREAD

**Issue by parihaaraka** [postgrespro/pg_pathman#47]
PostgreSQL 9.5.4 on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit
(postgrespro)

select pathman.create_range_partitions('main.participant', 'pdate', '2016-01-01'::date, '1 year'::interval);
->
NOTICE:  sequence "participant_seq" does not exist, skipping
WARNING:  Range constraint for relation 41726 MUST have exact format: VARIABLE >= CONST AND VARIABLE < CONST. Skipping...
WARNING:  Partitions 41692 and 41726 overlap. Disabling pathman for relation 29053...
NOTICE:  Copying data to partitions...
ERROR:  ERROR: Cannot find partition P0001

select * from main.participant
->
ERROR:  could not open relation with OID 2147483649

* several rows in
create table main.participant
(
  tid bigint not null,
  cid integer not null,
  pdate date not null,
  ...
  primary key (tid, cid)
)

**Comment by funbringer** [comment]
Is this related to your other issue? Could it be that you've tried to upgrade from an obsolete version?

**Comment by parihaaraka** [comment]
That was before upgrade. I've applied pg_pathman to my data from scratch on 9.6 (from postgrespro repo), and it's much more stable now, but there are still some warnings about non-existent functions and garbage with oids instead of classnames in pathman_config_params.

**Comment by funbringer** [comment]
> there are still some warnings about non-existent functions

This should not happen at all, I think that you've upgraded from some commit that was never assigned a tag or meant to be a solid release, so please make sure that you have a full set of functions listed in `init.sql` + `hash.sql` + `range.sql` and NO more than that, OR simply perform a clean installation (personally I would recommend the latter option).

We can't provide a proper migration script for any commit in our master branch, which means that pg_pathman can be safely upgraded only from tagged commits.

> and garbage with oids instead of classnames in pathman_config_params

In fact, `pathman_config_params` may contain anything without hurting pg_pathman too much, but I guess you meant `pathman_config`, right?

Anyway, you'd better just remove them from your config for the sake of consistency.

> I've applied pg_pathman to my data from scratch

We've changed check constraint structure and some other things several times since 0.1, no wonder you got so much pain attaching your old partitioning scheme to pg_pathman. Anyway, you could always  repartition your data using the fresh stable version.

Is there anything we could do in order to help you?

**Comment by parihaaraka** [comment]
>  simply perform a clean installation 
Exactly. Clean install from official postgrespro repo, pg_pathman from it's contrib package.

> you meant pathman_config, right?
No, i mean pathman_config_params. My tests lead to removal of the subject table from pathman_config, but there was no way to remove trigger registration and one more row (i've deleted them manually) from pathman_config_params.

>  you could always repartition your data using the fresh stable version
This is what i did. 

> Is there anything we could do in order to help you?
No, thanks a lot. It works rather stable when used carefully :) Unfortunately i didn't have time to reproduce my problem and prepare the script for you.

Thanks again. Good job!
