### ISSUE TITLE
django insert or update foreign key Key (id)=(100) is not present in table "msg".?

### ISSUE THREAD

**Issue by mapleflow** [postgrespro/pg_pathman#79]
Env:

	Ubuntu 14.04, Django 1.10.5, pg_pathman 1.3, postgresql 9.6
    
table `product` reference table `msg`

	alter table product add constraint 
    product_msg_fk
	foreign key(msg_id) 
    references msg(id) 
    deferrable initially deferred;
    
`msg` works well when directly `insert`，but when i insert into `product` record， error occur

	django.db.utils.IntegrityError: insert or update on table "product" violates 
    foreign key constraint "product_msg_fk"    
	DETAIL:  Key (msg_id)=(100) is not present in table "msg".
    
all data are exists in correct partition, i create partition by table `msg` field `create_time`.

Anything wrong with my sql, django project or pg_pathman config?

**Comment by zilder** [comment]
Hi @mapleflow,

Yes, it is a known issue. The problem is that you create foreign key, that references parent table `msg`, but parent itself doesn't contain any data (all the data is in partitions). Currently postgres doesn't support any kind of global indexes on inheritance tree, so when you are creating foreign key to parent, it means parent only, not its descendants. We don't have proper solution to this problem. My suggestion would be to remove foreign key constraint.

**Comment by funbringer** [comment]
Is there anything else we can do?

**Comment by mapleflow** [comment]
got it, it seem much trouble with foreign key,   

1.partition table can not inherit all from master table, like `foreign key`, `primary key`, `unique key`, but not include `not null` and `check`.

2.`unique key` or `index` should not be work on master table, must be work for each partition.

thanks for your solution.

**Comment by nerdykamil** [comment]
Hey, I am experiencing the same problem. Can you share what approach you used to resolve the error. Thanks

**Comment by mapleflow** [comment]
@nerdykamil  does not support, so give up this try.

**Comment by andreportela** [comment]
no updates so far?

**Comment by akuisara** [comment]
Hello, are there any updates on this issue?
